### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by jrast** [spyder-ide/spyder.autopep8#1]
This plugin is not loaded on spyder startup. 

Maybe because it's installed under the wrong path? On my machine the files are located in 
`site-packages/spyplugins` but i thing the correct place would be `site-packages/spyderplugins`.

**Comment by ccordoba12** [comment]
You need to use the master branch of Spyder for this plugin to work with it. That's because we changed the way we handle third-party plugins, and so things are incompatible with our 2.3 branch.

**Comment by jrast** [comment]
Ah ok. Thanks for the info. This should maybe be mentioned in the Readme of the plugin.

**Comment by goanpeca** [comment]
@jrast you are correct, it has been updated https://github.com/spyder-ide/spyder.autopep8
