### ISSUE TITLE
Update this plugin to be compatible with Spyder 4 and release a new version of it

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder.autopep8#10]
@steff456, please take care of this one.

**Comment by raphaelquast** [comment]
any news on this?

**Comment by maxicarlos08** [comment]
Autopep8 seems to be implemented in spyder 4.2

**Comment by raphaelquast** [comment]
awesome! thanks for the info!   (works like a charm 😃)
... for anyone searching for it in spyder... it's here:       
    `Source > Format file or selection with Autopep8 ( Ctrl + Alt + i )`

**Comment by ccordoba12** [comment]
That's correct. Now Autopep8 and Black are supported out of the box by Spyder **4.2.0**, so this extra plugin is not necessary anymore.
