### ISSUE TITLE
spyplugins/ui/autopep8/__init__.py needs quote on version string

### ISSUE THREAD

**Issue by slm23** [spyder-ide/spyder.autopep8#2]
spyplugins/ui/autopep8/**init**.py may need adjustment, I had to put quotes around the version string.

Got this error on install otherwise:

  File ".local/lib/python2.7/site-packages/spyder.autopep8-0.0.1-py2.7.egg/spyplugins/ui/autopep8/**init**.py", line 1
    **version** = 0.0.1
                      ^
SyntaxError: invalid syntax

fixed by changing to **version** = "0.0.1"

**Comment by ccordoba12** [comment]
@Nodd?

**Comment by Nodd** [comment]
Thank you for reporting the issue, and sorry about the delay. It should be working fine now.
