### ISSUE TITLE
Update pypi version

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder.autopep8#4]
@goanpeca, I think that you did it the first time. Is there some procedure to update the package on pypi ?
I think we'll have to be more strict on the version numbers and stable branches.

**Comment by goanpeca** [comment]
Yes, we need to hmm I will draft something

**Comment by ccordoba12** [comment]
@Nodd, take a look at the file called `Release.md` in the `qtpy` repo. There are simple instructions to update our packages in PyPi :-)

**Comment by ccordoba12** [comment]
This package is no longer maintained, so this doesn't' apply anymore.
