### ISSUE TITLE
This is a generic enough plugin, that it should probably be part of the core

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder.autopep8#5]
We need to define a basic class inside the code editor for

Linters and formatters, so this plugin (the generic non python part) should/could be part of spyder core

**Comment by GorkemP** [comment]
I strongly agree with you

**Comment by jeverling** [comment]
I think what also would be incredibly useful is the ability to invoke some action (like calling an autoformatter) automatically every time an editor is saved.

**Comment by ccordoba12** [comment]
This is part of the core now. Please see the Readme of this project for details.
