### ISSUE TITLE
Can't install spyder-autopep8

### ISSUE THREAD

**Issue by kraamis** [spyder-ide/spyder.autopep8#8]
kraamis@debian [~]$ sudo pip3 install spyder.autopep8
Collecting spyder.autopep8
  Could not find a version that satisfies the requirement spyder.autopep8 (from versions: )
No matching distribution found for spyder.autopep8

On pypi.org install link absent on module page.

**Comment by CAM-Gerlach** [comment]
@kraamis The README announcement is in the process of being updated for all repos, but as [our current funding message](https://github.com/spyder-ide/spyder/wiki/Current-Funding-and-Development-Status) states, active development on most Spyder plugins like this one is currently paused to focus on finishing Spyder 4, and will be resumed after that is released (planned for January 2019). Thanks for your patience and thanks for using Spyder! If you want to help that happen faster, you can support us at our [OpenCollective](https://opencollective.com/spyder).

**Comment by larissalong** [comment]
I also have the same error msg when trying 'pip install spyder.autopep8'. Is there any update for the solution now?

**Comment by lianglianggithub** [comment]
In my practice, the methods that used "pip" are all invalid. However, the method that used "copy-paste"  is efficient, according to "https://github.com/spyder-ide/spyder/wiki/User-plugins".
Download and unzip (or clone) a plugin and copy the directory starting with "spyder_" in "${HOME}/.spyder/plugins/".
Actually, you can copy the folder "spyder_autopep8" that in the unzip folder, and paste in the folder where your spyder is installed, such as "xxx\anaconda3\\Lib\site-packages", where you can see many folders are named starting with "spyder_". 
Finally, restart your spyder, you can find "run autopep8 code autoformatting" in "Source->".

**Comment by Mte90** [comment]
In my case the path was: `${HOME}/.config/spyder-py3`

**Comment by jmmelko** [comment]
Thank you @lianglianggithub, it worked.

On my Mac, the directory to put the spyder_autopep8 folder was:

~/Applications/anaconda3/lib/python3.7/site-packages/

I also had to do pip install autopep8, of course :-)

**Comment by CAM-Gerlach** [comment]
@jmmelko I'm not speaking authoritatively here, but it is probably not a very good idea to just stick the package in your global anaconda `site-packages` directory, especially contaminating your `base` environment, as it is not properly installed and has a good chance of causing trouble down the line. Putting it in the Spyder config directory is likely a better approach as it ensures only Spyder will load it and it won't mess with Anaconda or other packages.

**Comment by ccordoba12** [comment]
This package was always in beta and never released to PyPI.

Besides, auto-formatting is now part of Spyder (please see the Readme of this project for details).
